using System.Net;
using System.Net.Http.Json;
using Nakama.Api.Modules.Identity.Features;
using Nakama.Api.Modules.Projects.Features;
using Nakama.Api.Tests.Identity;
using Xunit;
namespace Nakama.Api.Tests.Projects;
[Collection(PostgresCollection.Name)]
public sealed class StagesApiTests(PostgresApiFactory factory)
{
    [PostgresFact] public async Task Creates_orders_and_reorders_stages(){await factory.ResetDatabaseAsync();using var c=factory.CreateClient();var u=await User(c,"owner@nakama.com");var p=await Project(c,u.Id);var a=await Stage(c,p.Id,"A");var b=await Stage(c,p.Id,"B");var list=await c.GetFromJsonAsync<List<StageResponse>>($"/api/projects/{p.Id}/stages");Assert.Equal(new[]{1,2},list!.Select(x=>x.Position));var reorder=await c.PutAsJsonAsync($"/api/projects/{p.Id}/stages/order",new{stages=new[]{new{stageId=b.Id,position=1,version=b.Version},new{stageId=a.Id,position=2,version=a.Version}}});Assert.Equal(HttpStatusCode.NoContent,reorder.StatusCode);var changed=await c.GetFromJsonAsync<List<StageResponse>>($"/api/projects/{p.Id}/stages");Assert.Equal(new[]{b.Id,a.Id},changed!.Select(x=>x.Id));}
    [PostgresFact] public async Task Enforces_membership_and_blocks_project_member_removal(){await factory.ResetDatabaseAsync();using var c=factory.CreateClient();var owner=await User(c,"owner@nakama.com");var member=await User(c,"member@nakama.com");var outsider=await User(c,"out@nakama.com");var p=await Project(c,owner.Id);await c.PostAsJsonAsync($"/api/projects/{p.Id}/members",new{userId=member.Id});var s=await Stage(c,p.Id,"A");var denied=await c.PostAsJsonAsync($"/api/projects/{p.Id}/stages/{s.Id}/members",new{userId=outsider.Id,role="Member"});var added=await c.PostAsJsonAsync($"/api/projects/{p.Id}/stages/{s.Id}/members",new{userId=member.Id,role="Responsible"});var blocked=await c.DeleteAsync($"/api/projects/{p.Id}/members/{member.Id}");var removed=await c.DeleteAsync($"/api/projects/{p.Id}/stages/{s.Id}/members/{member.Id}");var allowed=await c.DeleteAsync($"/api/projects/{p.Id}/members/{member.Id}");Assert.Equal(HttpStatusCode.Conflict,denied.StatusCode);Assert.Equal(HttpStatusCode.Created,added.StatusCode);Assert.Equal(HttpStatusCode.Conflict,blocked.StatusCode);Assert.Equal(HttpStatusCode.NoContent,removed.StatusCode);Assert.Equal(HttpStatusCode.NoContent,allowed.StatusCode);}
    [PostgresFact] public async Task Rejects_closed_projects_duplicate_names_and_stale_versions(){await factory.ResetDatabaseAsync();using var c=factory.CreateClient();var u=await User(c,"owner@nakama.com");var p=await Project(c,u.Id);var s=await Stage(c,p.Id,"Desarrollo");var duplicate=await c.PostAsJsonAsync($"/api/projects/{p.Id}/stages",new{name="desarrollo"});var update=await c.PutAsJsonAsync($"/api/projects/{p.Id}/stages/{s.Id}",new{name="Nuevo",version=s.Version});var stale=await c.PutAsJsonAsync($"/api/projects/{p.Id}/stages/{s.Id}",new{name="Otro",version=s.Version});var detail=await c.GetFromJsonAsync<ProjectDetailResponse>($"/api/projects/{p.Id}");await c.PostAsJsonAsync($"/api/projects/{p.Id}/complete",new{version=detail!.Version});var closed=await c.PostAsJsonAsync($"/api/projects/{p.Id}/stages",new{name="C"});Assert.Equal(HttpStatusCode.Conflict,duplicate.StatusCode);Assert.Equal(HttpStatusCode.NoContent,update.StatusCode);Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);Assert.Equal(HttpStatusCode.Conflict,closed.StatusCode);}
    private static async Task<UserDetailResponse> User(HttpClient c,string email){var r=await c.PostAsJsonAsync("/api/users",new{fullName=email,email,role = "Collaborator", password = PostgresApiFactory.DefaultPassword });r.EnsureSuccessStatusCode();return (await r.Content.ReadFromJsonAsync<UserDetailResponse>())!;}
    private static async Task<ProjectCreatedResponse> Project(HttpClient c,Guid id){var r=await c.PostAsJsonAsync("/api/projects",new{name="P"});r.EnsureSuccessStatusCode();return (await r.Content.ReadFromJsonAsync<ProjectCreatedResponse>())!;}
    private static async Task<StageResponse> Stage(HttpClient c,Guid p,string n){var r=await c.PostAsJsonAsync($"/api/projects/{p}/stages",new{name=n});r.EnsureSuccessStatusCode();return (await r.Content.ReadFromJsonAsync<StageResponse>())!;}
}
