<script setup>
import { computed, onMounted, ref } from 'vue'
import AsyncState from '../../shared/components/AsyncState.vue'; import Badges from '../../shared/components/Badges.vue'; import BaseModal from '../../shared/components/BaseModal.vue'; import ProjectForm from './ProjectForm.vue'; import { projectsService } from './projects.service'; import { apiMessage } from '../../app/services/api'; import { projectPayload, runAdminMutation } from '../../app/services/admin-ui'; import { useAuthStore } from '../../app/stores/auth.store'; import { useRouter } from 'vue-router'
const auth = useAuthStore(); const router = useRouter(); const projects = ref([]); const loading = ref(true); const error = ref(''); const showCreate = ref(false); const submitting = ref(false); const title = computed(() => auth.isAdmin ? 'Proyectos' : 'Mis proyectos')
async function load() { loading.value = true; try { projects.value = auth.isAdmin ? await projectsService.list() : await projectsService.userProjects(auth.user.id) } catch (e) { error.value = apiMessage(e) } finally { loading.value = false } }
async function create(form) { submitting.value = true; let created; const ok = await runAdminMutation(async () => { created = await projectsService.create(projectPayload(form)) }, load, value => error.value = value); submitting.value = false; if (ok) { showCreate.value = false; router.push(`/projects/${created.id}`) } }
onMounted(load)
</script>
<template><section class="page"><header class="page-header"><div><p class="eyebrow">PORTAFOLIO</p><h1>{{ title }}</h1><p>Consulta el estado y el trabajo activo de cada iniciativa.</p></div><button v-if="auth.isAdmin" class="button primary" @click="showCreate = true">+ Nuevo proyecto</button></header><p v-if="error" class="form-error">{{ error }}</p><AsyncState :loading="loading" :error="error" :empty="!projects.length" :empty-title="auth.isAdmin ? 'No hay proyectos todavía.' : 'No hay proyectos disponibles'" :empty-description="auth.isAdmin ? 'Crea tu primer proyecto para empezar a organizar el trabajo.' : undefined"><template #default><div class="project-grid"><RouterLink v-for="project in projects" :key="project.id" :to="`/projects/${project.id}`" class="project-card"><div><Badges :value="project.status" /><h2>{{ project.name }}</h2><p>{{ project.description || 'Sin descripción.' }}</p></div><dl><div><dt>Miembros</dt><dd>{{ project.memberCount }}</dd></div><div><dt>Periodo</dt><dd>{{ project.startDate ? new Date(project.startDate).toLocaleDateString('es-PE') : 'Sin fecha' }}</dd></div></dl></RouterLink></div></template></AsyncState><button v-if="auth.isAdmin && !loading && !projects.length" class="button primary empty-cta" @click="showCreate = true">Crear proyecto</button><BaseModal v-model="showCreate" title="Nuevo proyecto"><ProjectForm :submitting="submitting" @submit="create" /></BaseModal></section></template>
