using Nakama.Api.BuildingBlocks.Time;

namespace Nakama.Api.Modules.Tasks.Domain;

public sealed class WorkTask
{
    private WorkTask() { }
    private WorkTask(Guid projectId, Guid stageId, string title, string? description, TaskPriority priority, DateTimeOffset? dueDate, Guid creator, DateTimeOffset now)
    { Id = Guid.NewGuid(); ProjectId = projectId; StageId = stageId; SetDetails(title, description, priority, dueDate); CreatedByUserId = creator; Status = TaskStatus.Pending; Version = 1; CreatedAt = now; UpdatedAt = now; }
    public Guid Id { get; private set; } public Guid ProjectId { get; private set; } public Guid StageId { get; private set; } public string Title { get; private set; } = null!; public string? Description { get; private set; } public TaskStatus Status { get; private set; } public TaskStatus? StatusBeforeBlocked { get; private set; } public TaskPriority Priority { get; private set; } public DateTimeOffset? DueDate { get; private set; } public Guid CreatedByUserId { get; private set; } public long Version { get; private set; } public DateTimeOffset CreatedAt { get; private set; } public DateTimeOffset UpdatedAt { get; private set; } public DateTimeOffset? CompletedAt { get; private set; }
    public static WorkTask Create(Guid projectId, Guid stageId, string title, string? description, TaskPriority priority, DateTimeOffset? dueDate, Guid creator, IClock clock) { ArgumentNullException.ThrowIfNull(clock); if (projectId == Guid.Empty || stageId == Guid.Empty || creator == Guid.Empty) throw new ArgumentException("Project, stage and creator are required."); if (!Enum.IsDefined(priority)) throw new ArgumentOutOfRangeException(nameof(priority)); return new(projectId, stageId, title, description, priority, dueDate, creator, clock.UtcNow); }
    public void UpdateDetails(string title, string? description, TaskPriority priority, DateTimeOffset? dueDate, IClock clock) { if (!Enum.IsDefined(priority)) throw new ArgumentOutOfRangeException(nameof(priority)); SetDetails(title, description, priority, dueDate); Touch(clock); }
    public void MoveToStage(Guid stageId, IClock clock) { if (stageId == Guid.Empty) throw new ArgumentException("Stage is required."); StageId = stageId; Touch(clock); }
    public void ChangeAssignments(IClock clock) => Touch(clock);
    public void Block(IClock clock) { if (Status is TaskStatus.Completed or TaskStatus.Cancelled) throw new InvalidOperationException("Terminal tasks cannot be blocked."); if (Status != TaskStatus.Blocked) { StatusBeforeBlocked = Status; Status = TaskStatus.Blocked; } Touch(clock); }
    public void ResolveBlocker(bool hasOtherActiveBlockers, IClock clock) { if (Status == TaskStatus.Blocked && !hasOtherActiveBlockers) { if (StatusBeforeBlocked is not (TaskStatus.Pending or TaskStatus.InProgress or TaskStatus.InReview)) throw new InvalidOperationException("Blocked task has no restorable status."); Status = StatusBeforeBlocked.Value; StatusBeforeBlocked = null; } Touch(clock); }
    public void Start(IClock clock) => Transition(TaskStatus.InProgress, clock); public void SubmitForReview(IClock clock) => Transition(TaskStatus.InReview, clock); public void RequestChanges(IClock clock) => Transition(TaskStatus.InProgress, clock); public void Complete(IClock clock) { Transition(TaskStatus.Completed, clock); CompletedAt = clock.UtcNow; } public void Cancel(IClock clock) { Transition(TaskStatus.Cancelled, clock); StatusBeforeBlocked = null; }
    private void Transition(TaskStatus next, IClock clock) { var allowed = (Status, next) switch { (TaskStatus.Pending, TaskStatus.InProgress) or (TaskStatus.InProgress, TaskStatus.InReview) or (TaskStatus.InReview, TaskStatus.InProgress) or (TaskStatus.InReview, TaskStatus.Completed) or (TaskStatus.Pending or TaskStatus.InProgress or TaskStatus.InReview or TaskStatus.Blocked, TaskStatus.Cancelled) => true, _ => false }; if (!allowed) throw new InvalidOperationException($"Cannot transition from {Status} to {next}."); Status = next; Touch(clock); }
    private void SetDetails(string title, string? description, TaskPriority priority, DateTimeOffset? dueDate) { Title = title?.Trim() ?? string.Empty; if (string.IsNullOrWhiteSpace(Title) || Title.Length > 300) throw new ArgumentException("Title is required and must not exceed 300 characters."); Description = string.IsNullOrWhiteSpace(description) ? null : description.Trim(); if (Description?.Length > 4000) throw new ArgumentException("Description must not exceed 4000 characters."); Priority = priority; DueDate = dueDate; }
    private void Touch(IClock clock) { ArgumentNullException.ThrowIfNull(clock); UpdatedAt = clock.UtcNow; Version++; }
}
